
package jaxws.client;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "companyServiceWS", targetNamespace = "http://endpoint.jaxws/", wsdlLocation = "http://localhost:8081/jax-ws?wsdl")
public class CompanyServiceWS
        extends Service {

    private final static URL COMPANYSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException COMPANYSERVICEWS_EXCEPTION;
    private final static QName COMPANYSERVICEWS_QNAME = new QName("http://endpoint.jaxws/", "companyServiceWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/jax-ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMPANYSERVICEWS_WSDL_LOCATION = url;
        COMPANYSERVICEWS_EXCEPTION = e;
    }

    public CompanyServiceWS() {
        super(__getWsdlLocation(), COMPANYSERVICEWS_QNAME);
    }

    public CompanyServiceWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMPANYSERVICEWS_QNAME, features);
    }

    public CompanyServiceWS(URL wsdlLocation) {
        super(wsdlLocation, COMPANYSERVICEWS_QNAME);
    }

    public CompanyServiceWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMPANYSERVICEWS_QNAME, features);
    }

    public CompanyServiceWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CompanyServiceWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (COMPANYSERVICEWS_EXCEPTION != null) {
            throw COMPANYSERVICEWS_EXCEPTION;
        }
        return COMPANYSERVICEWS_WSDL_LOCATION;
    }

    /**
     * @return returns CompanyService
     */
    @WebEndpoint(name = "CompanyServiceImplPort")
    public CompanyService getCompanyServiceImplPort() {
        return super.getPort(new QName("http://endpoint.jaxws/", "CompanyServiceImplPort"), CompanyService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CompanyService
     */
    @WebEndpoint(name = "CompanyServiceImplPort")
    public CompanyService getCompanyServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.jaxws/", "CompanyServiceImplPort"), CompanyService.class, features);
    }

}
