
package jaxws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "CompanyService", targetNamespace = "http://endpoint.jaxws/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface CompanyService {


    /**
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createCompany", targetNamespace = "http://endpoint.jaxws/", className = "jaxws.endpoint.SaveCompany")
    @ResponseWrapper(localName = "saveCompanyResponse", targetNamespace = "http://endpoint.jaxws/", className = "jaxws.endpoint.SaveCompanyResponse")
    @Action(input = "http://endpoint.jaxws/CompanyService/saveCompanyRequest", output = "http://endpoint.jaxws/CompanyService/saveCompanyResponse")
    void saveCompany(
            @WebParam(name = "arg0", targetNamespace = "")
            Company arg0);

    /**
     * @return returns java.util.List<jaxws.endpoint.Company>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompanies", targetNamespace = "http://endpoint.jaxws/", className = "jaxws.endpoint.GetCompanies")
    @ResponseWrapper(localName = "getCompaniesResponse", targetNamespace = "http://endpoint.jaxws/", className = "jaxws.endpoint.GetCompaniesResponse")
    @Action(input = "http://endpoint.jaxws/CompanyService/getCompaniesRequest", output = "http://endpoint.jaxws/CompanyService/getCompaniesResponse")
    List<Company> getCompanies();

}
